### ISSUE TITLE
Clean Up Dependencies

### ISSUE THREAD

**Issue by andytudhope** [dap-ps/discover-v2#1]
First step in this new repo is the clean up the package.json

See the dependabot bumps [here](https://github.com/dap-ps/discover/pulls) as a starting point. But we will also need to remove a fair bit of old crust from the previous version.

**Comment by jakubgs** [comment]
Yes. For example, the main build step in the `Makefile` was:
https://github.com/dap-ps/discover-v2/blob/c061afe386727e77ec88780d89a4c4ea7a446629/Makefile#L55-L56

Not sure if this is still relevant. Same for other steps like:
https://github.com/dap-ps/discover-v2/blob/c061afe386727e77ec88780d89a4c4ea7a446629/Makefile#L76-L78
or
https://github.com/dap-ps/discover-v2/blob/c061afe386727e77ec88780d89a4c4ea7a446629/Makefile#L61-L74

We might want to port this build process to something like Gulp and refresh it.
But I would probably need help from @richard-ramos to understand the process.
